language: ruby
cache: bundler

os:
  - linux
  - osx

rvm:
  - jruby
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.5

matrix:
  exclude:
    - rvm: 1.9.2
      os: osx
    - rvm: 1.9.3
      os: osx
    - rvm: jruby
      os: osx

jobs:
  include:
    - os: osx
      osx_image: xcode7.3
      rvm: 1.9.3
    - stage: deploy
      if: branch = master
      os: linux
      rvm: 2.0.0
      script: "If this weren't a test, we'd deploy here..."
